In [7]:
import pandas as pd
import numpy as np

books = pd.read_csv("../data/Books.csv", sep=',', dtype='unicode')
ratings = pd.read_csv("../data/Ratings.csv", sep=',', dtype='unicode')
users = pd.read_csv("../data/Users.csv", sep=',', dtype='unicode')


In [8]:
books.head()

ISBN                                         Book-Title   
0  0195153448                                Classical Mythology  \
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

            Book-Author Year-Of-Publication                   Publisher   
0    Mark P. O. Morford                2002     Oxford University Press  \
1  Richard Bruce Wright                2001       HarperFlamingo Canada   
2          Carlo D'Este                1991             HarperPerennial   
3      Gina Bari Kolata                1999        Farrar Straus Giroux   
4       E. J. W. Barber                1999  W. W. Norton &amp; Company   

                                         Image-URL-S   
0  http://images.amazon.com/images/P/0195153448.0...  \
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-M   
0  http://images.amazon.com/images/P/0195153448.0...  \
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...  
3  http://images.amazon.com/images/P/0374157065.0...  
4  http://images.amazon.com/images/P/0393045218.0...

In [9]:
ratings.head()

User-ID        ISBN Book-Rating
0  276725  034545104X           0
1  276726  0155061224           5
2  276727  0446520802           0
3  276729  052165615X           3
4  276729  0521795028           6

In [10]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype 
---  ------       --------------    ----- 
 0   User-ID      1149780 non-null  object
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  object
dtypes: object(3)
memory usage: 26.3+ MB


In [11]:
ratings.columns=ratings.columns.str.strip().str.lower().str.replace('-','_')

In [12]:
print(ratings.isnull().sum())

user_id        0
isbn           0
book_rating    0
dtype: int64


In [48]:
ratings.loc[(ratings['user_id'].isnull()),: ]

ISBN                                         Book-Title   
0  0195153448                                Classical Mythology  \
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

            Book-Author Year-Of-Publication                   Publisher   
0    Mark P. O. Morford                2002     Oxford University Press  \
1  Richard Bruce Wright                2001       HarperFlamingo Canada   
2          Carlo D'Este                1991             HarperPerennial   
3      Gina Bari Kolata                1999        Farrar Straus Giroux   
4       E. J. W. Barber                1999  W. W. Norton &amp; Company   

                                         Image-URL-S   
0  http://images.amazon.com/images/P/0195153448.0...  \
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-M   
0  http://images.amazon.com/images/P/0195153448.0...  \
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...  
3  http://images.amazon.com/images/P/0374157065.0...  
4  http://images.amazon.com/images/P/0393045218.0...

In [55]:
unique_ratings = ratings[ratings['isbn'].isin(books['ISBN'])]
unique_ratings

user_id        isbn book_rating
0        276725  034545104X           0
1        276726  0155061224           5
2        276727  0446520802           0
3        276729  052165615X           3
4        276729  0521795028           6
...         ...         ...         ...
1149774  276704  0876044011           0
1149775  276704  1563526298           9
1149776  276706  0679447156           0
1149777  276709  0515107662          10
1149778  276721  0590442449          10

[1031136 rows x 3 columns]

In [56]:
print(ratings.shape)
print(unique_ratings.shape)

(1149780, 3)
(1031136, 3)


In [57]:
unique_ratings['book_rating'].unique()

array(['0', '5', '3', '6', '7', '9', '8', '10', '1', '4', '2'],
      dtype=object)

In [22]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   User-ID   278858 non-null  object
 1   Location  278858 non-null  object
 2   Age       168096 non-null  object
dtypes: object(3)
memory usage: 6.4+ MB


In [23]:
users['Location'].unique()

array(['nyc, new york, usa', 'stockton, california, usa',
       'moscow, yukon territory, russia', ...,
       'sergnano, lombardia, italy', 'stranraer, n/a, united kingdom',
       'tacoma, washington, united kingdom'], dtype=object)

In [30]:

missing_values_count = users['Location'].isna().sum()
print("Number of missing values in the 'Location' column:", missing_values_count)


Number of missing values in the 'Location' column: 0


In [24]:
users['User-ID'].unique()

array(['1', '2', '3', ..., '278856', '278857', '278858'], dtype=object)

In [27]:
#unique value of Age
users['Age'].unique()

array([nan, '18.0', '17.0', '61.0', '26.0', '14.0', '25.0', '19.0',
       '46.0', '55.0', '32.0', '24.0', '20.0', '34.0', '23.0', '51.0',
       '31.0', '21.0', '44.0', '30.0', '57.0', '43.0', '37.0', '41.0',
       '54.0', '42.0', '50.0', '39.0', '53.0', '47.0', '36.0', '28.0',
       '35.0', '13.0', '58.0', '49.0', '38.0', '45.0', '62.0', '63.0',
       '27.0', '33.0', '29.0', '66.0', '40.0', '15.0', '60.0', '0.0',
       '79.0', '22.0', '16.0', '65.0', '59.0', '48.0', '72.0', '56.0',
       '67.0', '1.0', '80.0', '52.0', '69.0', '71.0', '73.0', '78.0',
       '9.0', '64.0', '103.0', '104.0', '12.0', '74.0', '75.0', '231.0',
       '3.0', '76.0', '83.0', '68.0', '119.0', '11.0', '77.0', '2.0',
       '70.0', '93.0', '8.0', '7.0', '4.0', '81.0', '114.0', '230.0',
       '239.0', '10.0', '5.0', '148.0', '151.0', '6.0', '101.0', '201.0',
       '96.0', '84.0', '82.0', '90.0', '123.0', '244.0', '133.0', '91.0',
       '128.0', '94.0', '85.0', '141.0', '110.0', '97.0', '219.0', '86.0',
 

In [31]:

missing_values_count = users['Age'].isna().sum()
print("Number of missing values in the 'Age' column:", missing_values_count)


Number of missing values in the 'Age' column: 110762


In [38]:
users['Age'] = pd.to_numeric(users['Age'], errors='coerce')
users['Age'].fillna((users['Age'].mean()), inplace=True)
users['Age'].unique()

array([ 34.7514337,  18.       ,  17.       ,  61.       ,  26.       ,
        14.       ,  25.       ,  19.       ,  46.       ,  55.       ,
        32.       ,  24.       ,  20.       ,  34.       ,  23.       ,
        51.       ,  31.       ,  21.       ,  44.       ,  30.       ,
        57.       ,  43.       ,  37.       ,  41.       ,  54.       ,
        42.       ,  50.       ,  39.       ,  53.       ,  47.       ,
        36.       ,  28.       ,  35.       ,  13.       ,  58.       ,
        49.       ,  38.       ,  45.       ,  62.       ,  63.       ,
        27.       ,  33.       ,  29.       ,  66.       ,  40.       ,
        15.       ,  60.       ,   0.       ,  79.       ,  22.       ,
        16.       ,  65.       ,  59.       ,  48.       ,  72.       ,
        56.       ,  67.       ,   1.       ,  80.       ,  52.       ,
        69.       ,  71.       ,  73.       ,  78.       ,   9.       ,
        64.       , 103.       , 104.       ,  12.       ,  74. 

In [40]:
users.loc[(users['Age'] > 90) | (users['Age'] < 5)] = np.nan

In [42]:
users['Age'].fillna((users['Age'].mean()), inplace=True)
users['Age'].unique()

array([34.7514337 , 18.        , 17.        , 61.        , 26.        ,
       14.        , 25.        , 19.        , 46.        , 55.        ,
       32.        , 24.        , 20.        , 34.        , 23.        ,
       51.        , 31.        , 21.        , 44.        , 30.        ,
       57.        , 43.        , 37.        , 41.        , 54.        ,
       42.        , 50.        , 39.        , 53.        , 47.        ,
       36.        , 28.        , 35.        , 13.        , 58.        ,
       49.        , 38.        , 45.        , 62.        , 63.        ,
       27.        , 33.        , 29.        , 66.        , 40.        ,
       15.        , 60.        , 34.73485224, 79.        , 22.        ,
       16.        , 65.        , 59.        , 48.        , 72.        ,
       56.        , 67.        , 80.        , 52.        , 69.        ,
       71.        , 73.        , 78.        ,  9.        , 64.        ,
       12.        , 74.        , 75.        , 76.        , 83.  